# Generated by Django 4.1.7 on 2023-04-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_color_car_description_car_trim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gain', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
