# Generated by Django 4.1.7 on 2023-04-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mods',
            field=models.ManyToManyField(to='main_app.mod'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='maintenance date'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service',
            field=models.CharField(choices=[('O', 'Oil Change'), ('T', 'Tires'), ('B', 'Brakes')], default='O', max_length=1, verbose_name='maintenance type'),
        ),
    ]
